name: Deploy to AWS Amplify

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Trigger Amplify Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Trigger Amplify Release Job
        run: |
          aws amplify start-job \
            --app-id d1zpjygau4fwcy \
            --branch-name main \
            --job-type RELEASE
